/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface NFTDutchAuctionInterface extends utils.Interface {
  functions: {
    "auctionStatusOpen()": FunctionFragment;
    "buyer()": FunctionFragment;
    "getBlockDiff()": FunctionFragment;
    "getCurrBlock()": FunctionFragment;
    "getCurrentPrice()": FunctionFragment;
    "initialPrice()": FunctionFragment;
    "isAuctionClosed()": FunctionFragment;
    "nft_Address()": FunctionFragment;
    "nft_Id()": FunctionFragment;
    "numBlocksAuctionOpen()": FunctionFragment;
    "offerPriceDecrement()": FunctionFragment;
    "placeBid()": FunctionFragment;
    "reservePrice()": FunctionFragment;
    "seller()": FunctionFragment;
    "startingBlock()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "auctionStatusOpen"
      | "buyer"
      | "getBlockDiff"
      | "getCurrBlock"
      | "getCurrentPrice"
      | "initialPrice"
      | "isAuctionClosed"
      | "nft_Address"
      | "nft_Id"
      | "numBlocksAuctionOpen"
      | "offerPriceDecrement"
      | "placeBid"
      | "reservePrice"
      | "seller"
      | "startingBlock"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "auctionStatusOpen",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "buyer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBlockDiff",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuctionClosed",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nft_Address",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "nft_Id", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "numBlocksAuctionOpen",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "offerPriceDecrement",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "placeBid", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reservePrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "seller", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "startingBlock",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "auctionStatusOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBlockDiff",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuctionClosed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nft_Address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nft_Id", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "numBlocksAuctionOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "offerPriceDecrement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reservePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seller", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startingBlock",
    data: BytesLike
  ): Result;

  events: {};
}

export interface NFTDutchAuction extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: NFTDutchAuctionInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    auctionStatusOpen(overrides?: CallOverrides): Promise<[boolean]>;

    buyer(overrides?: CallOverrides): Promise<[string]>;

    getBlockDiff(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrBlock(overrides?: CallOverrides): Promise<[BigNumber]>;

    getCurrentPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    initialPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    isAuctionClosed(overrides?: CallOverrides): Promise<[boolean]>;

    nft_Address(overrides?: CallOverrides): Promise<[string]>;

    nft_Id(overrides?: CallOverrides): Promise<[BigNumber]>;

    numBlocksAuctionOpen(overrides?: CallOverrides): Promise<[BigNumber]>;

    offerPriceDecrement(overrides?: CallOverrides): Promise<[BigNumber]>;

    placeBid(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reservePrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    seller(overrides?: CallOverrides): Promise<[string]>;

    startingBlock(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  auctionStatusOpen(overrides?: CallOverrides): Promise<boolean>;

  buyer(overrides?: CallOverrides): Promise<string>;

  getBlockDiff(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrBlock(overrides?: CallOverrides): Promise<BigNumber>;

  getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

  initialPrice(overrides?: CallOverrides): Promise<BigNumber>;

  isAuctionClosed(overrides?: CallOverrides): Promise<boolean>;

  nft_Address(overrides?: CallOverrides): Promise<string>;

  nft_Id(overrides?: CallOverrides): Promise<BigNumber>;

  numBlocksAuctionOpen(overrides?: CallOverrides): Promise<BigNumber>;

  offerPriceDecrement(overrides?: CallOverrides): Promise<BigNumber>;

  placeBid(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reservePrice(overrides?: CallOverrides): Promise<BigNumber>;

  seller(overrides?: CallOverrides): Promise<string>;

  startingBlock(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    auctionStatusOpen(overrides?: CallOverrides): Promise<boolean>;

    buyer(overrides?: CallOverrides): Promise<string>;

    getBlockDiff(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

    initialPrice(overrides?: CallOverrides): Promise<BigNumber>;

    isAuctionClosed(overrides?: CallOverrides): Promise<boolean>;

    nft_Address(overrides?: CallOverrides): Promise<string>;

    nft_Id(overrides?: CallOverrides): Promise<BigNumber>;

    numBlocksAuctionOpen(overrides?: CallOverrides): Promise<BigNumber>;

    offerPriceDecrement(overrides?: CallOverrides): Promise<BigNumber>;

    placeBid(overrides?: CallOverrides): Promise<void>;

    reservePrice(overrides?: CallOverrides): Promise<BigNumber>;

    seller(overrides?: CallOverrides): Promise<string>;

    startingBlock(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    auctionStatusOpen(overrides?: CallOverrides): Promise<BigNumber>;

    buyer(overrides?: CallOverrides): Promise<BigNumber>;

    getBlockDiff(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrBlock(overrides?: CallOverrides): Promise<BigNumber>;

    getCurrentPrice(overrides?: CallOverrides): Promise<BigNumber>;

    initialPrice(overrides?: CallOverrides): Promise<BigNumber>;

    isAuctionClosed(overrides?: CallOverrides): Promise<BigNumber>;

    nft_Address(overrides?: CallOverrides): Promise<BigNumber>;

    nft_Id(overrides?: CallOverrides): Promise<BigNumber>;

    numBlocksAuctionOpen(overrides?: CallOverrides): Promise<BigNumber>;

    offerPriceDecrement(overrides?: CallOverrides): Promise<BigNumber>;

    placeBid(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reservePrice(overrides?: CallOverrides): Promise<BigNumber>;

    seller(overrides?: CallOverrides): Promise<BigNumber>;

    startingBlock(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    auctionStatusOpen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getBlockDiff(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getCurrentPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    isAuctionClosed(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nft_Address(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nft_Id(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numBlocksAuctionOpen(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    offerPriceDecrement(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    placeBid(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reservePrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    seller(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    startingBlock(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
