/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as auctionSol from "./Auction.sol";
export type { auctionSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export type { BasicDutchAuction } from "./Auction.sol/BasicDutchAuction";
export { BasicDutchAuction__factory } from "./factories/Auction.sol/BasicDutchAuction__factory";
export { Lock__factory } from "./factories/Lock__factory";
