/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftDutchAuctionErc20BidsUpgradeableSol from "./NFTDutchAuction_ERC20BidsUpgradeable.sol";
export type { nftDutchAuctionErc20BidsUpgradeableSol };
export type { MyNFT } from "./MyNFT";
export type { MyToken } from "./MyToken";
