/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftDutchAuctionSol from "./NFTDutchAuction.sol";
export type { nftDutchAuctionSol };
export type { MyNFT } from "./MyNFT";
