/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUniqueToken,
  IUniqueTokenInterface,
} from "../../../contracts/NFTDutchAuction_ERC20BidsUpgradeable.sol/IUniqueToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferFrom",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IUniqueToken__factory {
  static readonly abi = _abi;
  static createInterface(): IUniqueTokenInterface {
    return new utils.Interface(_abi) as IUniqueTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUniqueToken {
    return new Contract(address, _abi, signerOrProvider) as IUniqueToken;
  }
}
