/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myNftSol from "./MyNFT.sol";
export type { myNftSol };
import type * as myTokenSol from "./MyToken.sol";
export type { myTokenSol };
import type * as nftDutchAuctionErc20BidsUpgradeableSol from "./NFTDutchAuction_ERC20BidsUpgradeable.sol";
export type { nftDutchAuctionErc20BidsUpgradeableSol };
