/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftDutchAuctionErc20BidsSol from "./NFTDutchAuction_ERC20Bids.sol";
export type { nftDutchAuctionErc20BidsSol };
export type { MyNFT } from "./MyNFT";
export type { MyToken } from "./MyToken";
