/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMyNFT } from "./IMyNFT";
export type { IMyToken } from "./IMyToken";
export type { NFTDutchAuction_ERC20BidsUpgradeable } from "./NFTDutchAuction_ERC20BidsUpgradeable";
